experiment_params:
  experiment_name: '2'
  output_path: "experiments"



model_params:
  model_name: 'BetaVae'
  in_channels: 3
  latent_dim: 256
  kld_weight: 0.1

data_params:
  train_data_path: "dataset_split/train/data"
  val_data_path: "dataset_split/val/data"
  test_data_path: "dataset_split/test/data"
  train_batch_size: 32
  val_batch_size:  32
  test_batch_size: 32
  num_workers: 0

trainer_params:
  use_gpu: True
  max_epochs: 1
  LR: 0.001
  weight_decay: 0.00001
