experiment_params:
  experiment_name: 'baseline_unvignette'
  output_path: "experiments"



model_params:
  model_name: 'vanilla_autoencoder'
  in_channels: 3
  latent_dim: 64
  kld_weight: 0.0

data_params:
  train_data_path: "dataset_split/train/data"
  val_data_path: "dataset_split/val/data"
  test_data_path: "dataset_split/test/data"
  target_data_path: "jervis_target_unvignetted_imgs"
  train_batch_size: 32
  val_batch_size:  32
  test_batch_size: 32
  num_workers: 0

trainer_params:
  use_gpu: True
  max_epochs: 100
  LR: 0.001
  weight_decay: 0.00001
